name: CI Pipeline



on:

  push:

    branches: testpipe



jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - run: |

          npm install

          npm test
